plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
    id 'scala'
}

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.mapping_version
        minecraftVersion = project.minecraft_version
    }

    accessTransformers {
        file('src/main/resources/META-INF/accesstransformer.cfg')
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            additionalRuntimeClasspathConfiguration.extendsFrom(configurations.runtimeClasspath)
        }

        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        gameTestServer {
            type = "gameTestServer"

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/data/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
}

sourceSets.main.scala { srcDir 'src/data/scala' }
sourceSets.main.resources {
    srcDir 'src/data/resources'
    exclude '.cache/**'
}

configurations {
    embedded
    compileClasspath.extendsFrom embedded
    runtimeClasspath.extendsFrom embedded
    implementation.extendsFrom embedded
}

repositories {
    mavenCentral()
    maven {
        name "MightyPirates"
        url "https://maven.cil.li/"
        metadataSources {
            mavenPom()
            artifact()
        }
    }
    maven {
        url "https://maven.squiddev.cc"
        content {
            includeGroup "cc.tweaked"
        }
    }
    maven {
        url "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://modmaven.dev"
        content {
            includeGroup "mezz.jei"
            includeGroup 'appeng'
        }
    }
    maven {
        url "https://chickenbones.net/maven/"
        content {
            includeGroup "codechicken"
            includeGroup "mrtjp"
        }
    }
    maven {
        url "https://modmaven.dev/"
        content {
            includeGroup "appeng"
            includeGroup "mekanism"
        }
    }
    maven {
        url "https://proxy-maven.covers1624.net/"
        content {
            includeModule "net.minecraftforge", "Scorge"
        }
    }
    maven {
        name = "kotori316"
        url = "https://maven.kotori316.com"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    flatDir { dirs 'libs' }
}

dependencies {
    compileOnly("org.scala-lang:scala-library:2.13.12")
    compileOnly("org.typelevel:cats-core_2.13:2.8.1-kotori")
    runtimeOnly("com.kotori316:scalablecatsforce-neoforge:3.3.3-build-15:with-library") {
        transitive(false)
    }

    embedded "com.typesafe:config:1.4.5"
    embedded ":OC-LuaJ:20220907.1"
    embedded ":OC-JNLua-Natives:20220928.1"

    def jeiSlug = "jei-${minecraft_version}"

    compileOnly("curse.maven:jade-324717:${jade_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-common-api:${cct_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-core-api:${cct_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cct_version}")
    runtimeOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cct_version}")
    runtimeOnly("maven.modrinth:modernfix:${modernfix_version}")

    // CoFH Core & Thermal
    // not currently available for 1.21+
//    compileOnly("curse.maven:cofh-core-69162:4801048")
//    compileOnly("curse.maven:thermal-foundation-222880:4788649")

    compileOnly("org.appliedenergistics:appliedenergistics2:${ae2_version}:api")
    compileOnly("mekanism:Mekanism:${mekanism_version}:api")
    runtimeOnly("mezz.jei:${jeiSlug}-neoforge:${jei_version}")
    compileOnly("mezz.jei:${jeiSlug}-neoforge-api:${jei_version}")
    compileOnly("curse.maven:cb-multipart-258426:5292585")
    compileOnly("curse.maven:codechicken-lib-1-8-242818:5753868")
    compileOnly("curse.maven:ender-storage-1-8-245174:5292573")
    compileOnly("mrtjp:ProjectRed:${projred_version}:core")
    compileOnly("mrtjp:ProjectRed:${projred_version}:api")

    testImplementation("org.scala-lang:scala-library:2.13.12")
    testImplementation("org.scalatest:scalatest_3:3.2.18")
    testImplementation("org.scalatestplus:junit-4-13_3:3.2.18.0")
    testImplementation("junit:junit:4.13.2")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = mod_group_id
            artifactId = mod_id
            version = project.version
        }
    }

    repositories {
        maven {
            name = "akkiserver"
            url = "https://maven.akkiserver.uk/releases/"
            credentials {
                username = findProperty("maven_user")
                password = findProperty("maven_password")
            }
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifact(provider {
                    tasks.named("jar").get().outputs.files.singleFile
                }) {
                    builtBy tasks.named("jar")
                    classifier = null
                    extension = "jar"
                }
                artifact(tasks.named("apiJar")) {
                    classifier = 'api' as Publication
                    extension = "jar"
                }
                artifact(tasks.named("apiSourcesJar")) {
                    classifier = 'sources'
                    extension = "jar"
                }
            }
        }
    }
}

tasks.register('updateBuildNumber') {
    mustRunAfter 'clean'
    doLast {
        def f = file('build.txt')
        if (!f.exists()) f.text = '0'
        def next = f.text.trim().toInteger() + 1
        f.text = next.toString()
        project.version = "${minecraft_version}-${mod_version}-${next}"
    }
}

tasks.named('build') {
    dependsOn updateBuildNumber
}

gradle.taskGraph.whenReady { taskGraph ->
    def buildFile = file('build.txt')
    def buildNum = buildFile.exists() ? buildFile.text.trim() : "0"

    if (taskGraph.hasTask(':updateBuildNumber')) {
        project.version = "${mod_version}-${buildNum.toInteger() + 1}"
    } else {
        project.version = "${mod_version}-${buildNum}"
    }
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version       : neoforge_version,
            neoforge_version_range : neoforge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/data/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.named("createMinecraftArtifacts").configure {
    dependsOn(generateModMetadata)
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    from({
        configurations.embedded.collect { it.isDirectory() ? it : zipTree(it) }
    }) {
        exclude 'META-INF', 'META-INF/**'
    }

//    finalizedBy 'reobfJar'
}

tasks.register('apiJar', Jar) {
    archiveClassifier = 'api'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
    include 'li/cil/oc/api/**'
}

tasks.register('apiSourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allJava
    include 'li/cil/oc/api/**'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ScalaCompile).configureEach {
    scalaCompileOptions.forkOptions.memoryMaximumSize = '2g'
    scalaCompileOptions.forkOptions.jvmArgs = ['-Xss4m']
}
