buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = 'https://maven.parchmentmc.org' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'scala'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

// currently, mixin is unused
mixin {
    //add sourceSets.main, "${mod_id}.refmap.json"
    //config "${mod_id}.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    embedded
    compileClasspath.extendsFrom embedded
    runtimeClasspath.extendsFrom embedded
    implementation.extendsFrom embedded
}

repositories {
    mavenCentral()
    maven {
        name "MightyPirates"
        url "https://maven.cil.li/"
        metadataSources {
            mavenPom()
            artifact()
        }
    }
    maven {
        name "SquidDev" /* CC: Tweaked */
        url "https://squiddev.cc/maven/"
    }
    maven {
        url "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://modmaven.dev"
        content {
            includeGroup "mezz.jei"
            includeGroup 'appeng'
        }
    }
    maven {
        url "https://chickenbones.net/maven/"
        content {
            includeGroup "codechicken"
            includeGroup "mrtjp"
        }
    }
    maven {
        url "https://modmaven.dev/"
        content {
            includeGroup "appeng"
            includeGroup "mekanism"
        }
    }
    maven {
        url "https://proxy-maven.covers1624.net/"
        content {
            includeModule "net.minecraftforge", "Scorge"
        }
    }
    maven {
        name = "Azure-SLP"
        url = uri("https://pkgs.dev.azure.com/Kotori316/minecraft/_packaging/mods/maven/v1")
        content {
            it.includeModule("com.kotori316", "ScalableCatsForce".toLowerCase())
            it.includeModule("org.typelevel", "cats-core_2.13")
            it.includeModule("org.typelevel", "cats-kernel_2.13")
        }
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    flatDir { dirs 'libs' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly(group: 'org.scala-lang', name: 'scala-library', version: "2.13.10")
    compileOnly(group: 'org.typelevel', name: "cats-core_2.13", version: '2.8.1-kotori')
    runtimeOnly(group: "com.kotori316", name: "ScalableCatsForce".toLowerCase(), version: "2.13.10-build-12", classifier: "with-library") {
        transitive(false)
    }

    //https://docs.minecraftforge.net/en/fg-6.x/dependencies/#non-minecraft-dependencies
    minecraftLibrary "com.typesafe:config:1.4.5"
    minecraftLibrary ":OC-LuaJ-20220907.1"
    //minecraftLibrary ":OC-JNLua-20230530.0"
    minecraftLibrary ":OC-JNLua-Natives-20220928.1"
    embedded "com.typesafe:config:1.4.5"
    embedded ":OC-LuaJ-20220907.1"
    //embedded ":OC-JNLua-20230530.0"
    embedded ":OC-JNLua-Natives-20220928.1"

    def jeiSlug = "jei-${minecraft_version}"

    compileOnly fg.deobf("curse.maven:tis-3d-238603:${tis3d_version}")
    compileOnly fg.deobf("curse.maven:jade-324717:${jade_version}")
    compileOnly fg.deobf("org.squiddev:cc-tweaked-${minecraft_version}:${cct_version}")

    runtimeOnly fg.deobf("maven.modrinth:modernfix:${modernfix_version}")
    
    // CoFH Core & Thermal
    compileOnly fg.deobf("curse.maven:cofh-core-69162:4801048")
    compileOnly fg.deobf("curse.maven:thermal-foundation-222880:4788649")

    compileOnly fg.deobf("appeng:appliedenergistics2:${ae2_version}:api")
    compileOnly fg.deobf("mekanism:Mekanism:${mekanism_version}:api")
    compileOnly fg.deobf("codechicken:CBMultipart:${cbmultipart_version}:universal")
    compileOnly fg.deobf("codechicken:ChickenASM:${casm_version}")
    runtimeOnly fg.deobf("mezz.jei:${jeiSlug}-forge:${jei_version}")
    compileOnly fg.deobf("mezz.jei:${jeiSlug}-forge-api:${jei_version}")
    compileOnly fg.deobf("codechicken:CodeChickenLib:${ccl_version}:universal")
    compileOnly fg.deobf("codechicken:EnderStorage:${enderstorage_version}:universal")
    compileOnly fg.deobf("mrtjp:ProjectRed:${projred_version}:core")

    testImplementation "org.scala-lang:scala3-library_3:3.3.7"
    testImplementation "org.scalatest:scalatest_3:3.2.18"
    testImplementation "org.scalatestplus:junit-4-13_3:3.2.18.0"
    testImplementation "junit:junit:4.13.2"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             forge_version          : forge_version,
                             forge_version_range    : forge_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description,]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    from({
        configurations.embedded.collect { it.isDirectory() ? it : zipTree(it) }
    }) {
        exclude 'META-INF', 'META-INF/**'
    }

    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ScalaCompile).configureEach {
    scalaCompileOptions.forkOptions.memoryMaximumSize = '2g'
    scalaCompileOptions.forkOptions.jvmArgs = ['-Xss4m']
}