org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G --add-opens java.base/sun.reflect.annotation=ALL-UNNAMED
org.gradle.configureondemand=false
# Minecraft & Forge Settings
minecraft_version=1.18.2
minecraft_version_range=[1.18.2]
forge_version=40.3.0
forge_version_range=[40,)
loader_version_range=[2.13.10-build-12]
mapping_channel=parchment
mapping_version=2022.11.06-1.18.2
#mapping_channel=official
#mapping_version=1.18.2

# Mod Information
mod_id=opencomputers
mod_name=OpenComputers
mod_group_id=li.cil.oc
mod_version=1.9.0-snapshot
mod_authors=MightyPirates
mod_description=Computers.
mod_license=MIT

# External Dependencies
ae2_version=11.5.0
cct_version=1.101.3
jade_version=5079263
jei_version=10.2.1.1005
mekanism_version=1.18.2-10.2.5.465
modernfix_version=5.18.0+mc1.18.2
tis3d_version=3738437
projred_version=1.18.2-4.16.0
ccl_version=1.18.2-4.1.4.488
cbmultipart_version=1.18.2-3.1.1.138
casm_version=2.0.1.14
enderstorage_version=1.18.2-2.9.0.182
# Publishing
curse_project_id=223008
modrinth_project_id=YiAbZis2