org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G --add-opens java.base/sun.reflect.annotation=ALL-UNNAMED
org.gradle.configureondemand=false
# Minecraft & Forge Settings
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.233
neoforge_version_range=[21,)
# scala is 2.13.12
loader_version_range=[3.3.3-build-15,4)
mapping_channel=parchment
mapping_version=2024.11.17

# Mod Information
mod_id=opencomputers
mod_name=OpenComputers
mod_group_id=li.cil.oc
mod_version=1.9.0
mod_authors=MightyPirates
mod_description=Computers.
mod_license=MIT

# External Dependencies
ae2_version=19.2.17
cct_version=1.119.0
jade_version=7545219
jei_version=19.27.0.336
mekanism_version=1.21.1-10.7.19.85
modernfix_version=5.27.11+mc1.21.1
projred_version=1.21.1-4.22.0
ccl_version=1.21.1-4.6.1.526
cbmultipart_version=1.21.1-3.5.0.155
casm_version=2.0.1.14
enderstorage_version=1.21.1-2.13.0.191
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
# Publishing
curse_project_id=223008
modrinth_project_id=YiAbZis2